apiVersion: v2
name: project-origin-stamp
description: A helm chart for deploying the Project Origin Stamp
type: application
version: 0.1.0
appVersion: "0.1.0"

annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/licence: Apache-2.0
  artifacthub.io/links: |
    - name: Source Code
      url: https://github.com/project-origin/stamp
  artifacthub.io/prerelease: "false"
  artifacthub.io/operator: "false"
