---
apiVersion: v1
kind: Service
metadata:
  name: po-stamp
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: po-stamp
  ports:
    - name: rest
      protocol: TCP
      port: 5000
      targetPort: 5000
