name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@c1e411bd412e1dca8aef08548b1dcdfb967dac38

  publish-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@c1e411bd412e1dca8aef08548b1dcdfb967dac38
    with:
      imagename: ghcr.io/project-origin/stamp
      version: ${{ needs.define-version.outputs.version }}
      context: ./src
      dockerfile: ./src/Stamp.Dockerfile
      push: true

  publish-chart:
    needs:
      - define-version
      - publish-container
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@c1e411bd412e1dca8aef08548b1dcdfb967dac38
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: chart
      helm_registry_repository: project-origin/helm-registry
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
